name: CICD

on:
  pull_request:
    branches:
    - main
    - dev


jobs:
  # The "build" workflow
  build:
    # The type of runner that the job will run on
    runs-on: 'ubuntu-20.04'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.0'
    
        
    # Run build of the application
    - name: Run build
      run: go build . 
      
    
    # Run testing on the code
    - name: Run testing
      run: cd test && go test -v
